version: '2'
services:
    db:
        build: 
            context: ./db
            dockerfile: Dockerfile
        environment:
            - MYSQL_ROOT_HOST=%
            - MYSQL_ROOT_PASSWORD=3dodPaTXF5

    proxy:
        build:
            context: ./proxy
            dockerfile: Dockerfile
        links:
            - web
            - restbase
        ports:
            - "8080:80"

    web:
        build: 
            context: ./web
            dockerfile: Dockerfile
        links:
            - db
            - elasticsearch
            - memcache
            - parsoid
            - restbase
        environment:
            - MW_SITE_SERVER=//localhost:8080
            - MW_SITE_NAME=MediaWiki
            - MW_SITE_LANG=en
            - MW_DEFAULT_SKIN=vector
            - MW_ENABLE_UPLOADS=1
            - MW_USE_INSTANT_COMMONS=0
            - MW_ADMIN_USER=admin
            - MW_ADMIN_PASS=q32Gx7Amg7
            - MW_DB_NAME=mediawiki
            - MW_DB_USER=mwuser
            - MW_DB_PASS=8Xgat7mUKa
            - MW_DB_INSTALLDB_USER=root
            - MW_DB_INSTALLDB_PASS=3dodPaTXF5
            - MW_AUTOUPDATE=true
            - MW_PROXY_SERVERS=proxy
            - PHP_LOG_ERRORS=On
            - PHP_ERROR_REPORTING=E_ALL #Production Value: E_ALL & ~E_DEPRECATED & ~E_STRICT

    memcache:
        build:
            context: ./memcache
            dockerfile: Dockerfile

    parsoid:
        build:
            context: ./parsoid
            dockerfile: Dockerfile
        environment:
            - NUM_WORKERS=0

    restbase:
        build:
            context: ./restbase
            dockerfile: Dockerfile
        environment:
            - NUM_WORKERS=0

    elasticsearch:
        build:
            context: ./elasticsearch
            dockerfile: Dockerfile
